### ISSUE TITLE
ERROR de_loader::map: failed to read entire block

### ISSUE THREAD

**Issue by 41Leahcim** [DigitalExtinction/Game#200]
I get the following error when trying to run the game as stated in the README.md.
```
2022-10-11T10:53:18.604227Z  INFO winit::platform_impl::platform::x11::window: Guessed window scale factor: 1    
2022-10-11T10:53:18.637348Z  INFO bevy_render::renderer: AdapterInfo { name: "NVIDIA GeForce RTX 2070", vendor: 4318, device: 7956, device_type: DiscreteGpu, backend: Vulkan }
2022-10-11T10:53:18.939532Z  INFO de_loader::map: Loading map from /home/michael/games/digital_extinction/assets/map.tar
2022-10-11T10:53:18.971503Z  INFO de_loader::map: Map loaded, spawning
2022-10-11T10:53:18.971517Z ERROR de_loader::map: failed to read entire block
thread 'main' panicked at 'failed to read entire block', crates/loader/src/map.rs:74:13
stack backtrace:
   0:     0x558b835e5710 - std::backtrace_rs::backtrace::libunwind::trace::h845489be954216a1
                               at /rustc/a6b7274a462829f8ef08a1ddcdcec7ac80dbf3e1/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   1:     0x558b835e5710 - std::backtrace_rs::backtrace::trace_unsynchronized::hc22c3fc36941637e
                               at /rustc/a6b7274a462829f8ef08a1ddcdcec7ac80dbf3e1/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x558b835e5710 - std::sys_common::backtrace::_print_fmt::h21566367032e35d4
                               at /rustc/a6b7274a462829f8ef08a1ddcdcec7ac80dbf3e1/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x558b835e5710 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h72366b9f7489658b
                               at /rustc/a6b7274a462829f8ef08a1ddcdcec7ac80dbf3e1/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x558b8360a29e - core::fmt::write::h1440c0152f5352ee
                               at /rustc/a6b7274a462829f8ef08a1ddcdcec7ac80dbf3e1/library/core/src/fmt/mod.rs:1209:17
   5:     0x558b835e2875 - std::io::Write::write_fmt::h01a0c683f4011cbd
                               at /rustc/a6b7274a462829f8ef08a1ddcdcec7ac80dbf3e1/library/std/src/io/mod.rs:1680:15
   6:     0x558b835e7073 - std::sys_common::backtrace::_print::hb6b7d9350a1bf6ea
                               at /rustc/a6b7274a462829f8ef08a1ddcdcec7ac80dbf3e1/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x558b835e7073 - std::sys_common::backtrace::print::h5fef162fa4c4a90c
                               at /rustc/a6b7274a462829f8ef08a1ddcdcec7ac80dbf3e1/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x558b835e7073 - std::panicking::default_hook::{{closure}}::h91c8dfae313a0a3c
                               at /rustc/a6b7274a462829f8ef08a1ddcdcec7ac80dbf3e1/library/std/src/panicking.rs:267:22
   9:     0x558b835e6d4a - std::panicking::default_hook::hd50d8a920cc08614
                               at /rustc/a6b7274a462829f8ef08a1ddcdcec7ac80dbf3e1/library/std/src/panicking.rs:286:9
  10:     0x558b835e7719 - std::panicking::rust_panic_with_hook::h23e14c7d62d93ab4
                               at /rustc/a6b7274a462829f8ef08a1ddcdcec7ac80dbf3e1/library/std/src/panicking.rs:669:13
  11:     0x558b835e7617 - std::panicking::begin_panic_handler::{{closure}}::hfe0bce4b7c5df181
                               at /rustc/a6b7274a462829f8ef08a1ddcdcec7ac80dbf3e1/library/std/src/panicking.rs:560:13
  12:     0x558b835e5bbc - std::sys_common::backtrace::__rust_end_short_backtrace::h2e38c83ce0dfcc0c
                               at /rustc/a6b7274a462829f8ef08a1ddcdcec7ac80dbf3e1/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x558b835e7332 - rust_begin_unwind
                               at /rustc/a6b7274a462829f8ef08a1ddcdcec7ac80dbf3e1/library/std/src/panicking.rs:556:5
  14:     0x558b82653803 - core::panicking::panic_fmt::h0c090a9cb6ea02e8
                               at /rustc/a6b7274a462829f8ef08a1ddcdcec7ac80dbf3e1/library/core/src/panicking.rs:142:14
  15:     0x558b826bc108 - core::panicking::panic_display::h50f867ff600c10f1
  16:     0x558b826ba676 - core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut::h6ef2c0e37516dc03
  17:     0x558b8269d060 - <bevy_ecs::system::system_chaining::ChainSystem<SystemA,SystemB> as bevy_ecs::system::system::System>::run_unsafe::hf7adf31f96317260
  18:     0x558b8352c903 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::ha189b0645eba2767
  19:     0x558b8352cc77 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hdb6f95718e6bd89f
  20:     0x558b83525edb - async_task::raw::RawTask<F,T,S>::run::h3f6f9fcc8299fc70
  21:     0x558b83558a19 - async_executor::Executor::try_tick::h3a93d643a7bc6428
  22:     0x558b8353fd32 - std::thread::local::LocalKey<T>::with::ha55da6c55738811c
  23:     0x558b83546e5d - <bevy_ecs::schedule::executor_parallel::ParallelExecutor as bevy_ecs::schedule::executor::ParallelSystemExecutor>::run_systems::h7619f401bdc850ad
  24:     0x558b8353d322 - <bevy_ecs::schedule::stage::SystemStage as bevy_ecs::schedule::stage::Stage>::run::h787c559e7ae7a72a
  25:     0x558b83517360 - bevy_ecs::schedule::Schedule::run_once::hebf2163f4550bb48
  26:     0x558b8350f76b - bevy_app::app::App::update::h2593d48d3de35f00
  27:     0x558b82870ed1 - bevy_winit::winit_runner_with::{{closure}}::hc05f66741cd3bb28
  28:     0x558b8289116a - winit::platform_impl::platform::x11::EventLoop<T>::run_return::hb74bcc832031f639
  29:     0x558b82891919 - winit::platform_impl::platform::x11::EventLoop<T>::run::h30f33563daed8d7b
  30:     0x558b8286dfbc - winit::platform_impl::platform::EventLoop<T>::run::h7a25486922c32ae4
  31:     0x558b8286881c - winit::event_loop::EventLoop<T>::run::h2d0aa1835c80e4a0
  32:     0x558b8286924c - bevy_winit::run::ha838d6535edfa4cb
  33:     0x558b82869ede - bevy_winit::winit_runner_with::h2b574f658effb3b9
  34:     0x558b8286d054 - core::ops::function::Fn::call::h3f7b9a1bba23820b
  35:     0x558b8350f8eb - bevy_app::app::App::run::he1a08fb66fb7e1d0
  36:     0x558b82654ff8 - de_game::main::h5c4ce015a043dda8
  37:     0x558b826552e3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h79bc07eeb7ae1243
  38:     0x558b82655119 - std::rt::lang_start::{{closure}}::h8ec10ec5fb1d12a6
  39:     0x558b835dc13b - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::ha397dafd39beb31f
                               at /rustc/a6b7274a462829f8ef08a1ddcdcec7ac80dbf3e1/library/core/src/ops/function.rs:286:13
  40:     0x558b835dc13b - std::panicking::try::do_call::h6a8663a68c6ef829
                               at /rustc/a6b7274a462829f8ef08a1ddcdcec7ac80dbf3e1/library/std/src/panicking.rs:464:40
  41:     0x558b835dc13b - std::panicking::try::h6c65310ffa529bc7
                               at /rustc/a6b7274a462829f8ef08a1ddcdcec7ac80dbf3e1/library/std/src/panicking.rs:428:19
  42:     0x558b835dc13b - std::panic::catch_unwind::h2f8e5fc55d4ae8b1
                               at /rustc/a6b7274a462829f8ef08a1ddcdcec7ac80dbf3e1/library/std/src/panic.rs:137:14
  43:     0x558b835dc13b - std::rt::lang_start_internal::{{closure}}::h5769b658ce95c456
                               at /rustc/a6b7274a462829f8ef08a1ddcdcec7ac80dbf3e1/library/std/src/rt.rs:148:48
  44:     0x558b835dc13b - std::panicking::try::do_call::hf345537ade70fb59
                               at /rustc/a6b7274a462829f8ef08a1ddcdcec7ac80dbf3e1/library/std/src/panicking.rs:464:40
  45:     0x558b835dc13b - std::panicking::try::h11070e39dbc4abcc
                               at /rustc/a6b7274a462829f8ef08a1ddcdcec7ac80dbf3e1/library/std/src/panicking.rs:428:19
  46:     0x558b835dc13b - std::panic::catch_unwind::hcbd1839b5edfa8df
                               at /rustc/a6b7274a462829f8ef08a1ddcdcec7ac80dbf3e1/library/std/src/panic.rs:137:14
  47:     0x558b835dc13b - std::rt::lang_start_internal::h2331c440b5aeeeba
                               at /rustc/a6b7274a462829f8ef08a1ddcdcec7ac80dbf3e1/library/std/src/rt.rs:148:20
  48:     0x558b82655108 - main
  49:     0x7f4805df9290 - <unknown>
  50:     0x7f4805df934a - __libc_start_main
  51:     0x558b82653b35 - _start
                               at /build/glibc/src/glibc/csu/../sysdeps/x86_64/start.S:115
  52:                0x0 - <unknown>
```

**Comment by 41Leahcim** [comment]
I am using Arch btw

**Comment by Indy2222** [comment]
There must be `assets` directory next to the binary with all necessary assets. It can either be downloaded from the repository or you can download a zip file with latest Linux build (artifact of GH Action run on `main` branch).

https://github.com/DigitalExtinction/Game/suites/8712370228/artifacts/393655699

I will keep this issue open since better documentation of this is obviously needed.

Thanks for reporting!

**Comment by Indy2222** [comment]
Better error reporting while unable to load map is requested here #15.

**Comment by 41Leahcim** [comment]
> There must be `assets` directory next to the binary with all necessary assets. It can either be downloaded from the repository or you can download a zip file with latest Linux build (artifact of GH Action run on `main` branch).
> 
> https://github.com/DigitalExtinction/Game/suites/8712370228/artifacts/393655699
> 
> I will keep this issue open since better documentation of this is obviously needed.
> 
> Thanks for reporting!

Something when wrong while pulling the assets directory.
Instead of downloading the full map.tar file, git only downloaded a small part of it and marked the map.tar file as a text file.
```
$ file map.tar 
map.tar: ASCII text
```
I was able to extract the map.tar file in the zip file from https://github.com/DigitalExtinction/Game/suites/8712370228/artifacts/393655699 .
Thanks for your help.

**Comment by Indy2222** [comment]
Note that larger assets are tracked as [git LFS files](https://git-lfs.github.com/).
